name: CD pipline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self hosted

    steps:
    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-gh:latest
    - name: Delete Old Docker container
      run: docker rm -f cicd-gh-container || true
    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name cicd-gh-container ${{ secrets.DOCKER_USERNAME }}/cicd-gh