name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t cicd-gh .
    - name: Push to Dockerhub
      run: docker push loh21/cicd-gh:latest
    
